---
engine: knitr
title: "3. Time-Series Analysis"
---

# Learning objectives

::: nonincremental
- Mention time series
:::

::: {.callout-note collapse="true"}
## Package Libraries

```{r}
#| message: false
#| warning: false

library("DiagrammeR")
```
:::



## Stepping Forward

```{r}
#| echo: false
#| eval: true
DiagrammeR::mermaid("
graph LR

TS[time<br />series]
ARIMA[autoregressive<br />models]
TIS[time<br />invariant<br />systems]
CT[control<br />theory]
NSSM[neural<br />state space<br />models]

TS --> ARIMA

ARIMA --> diffusion
ARIMA --> LLMs

diffusion --> SDEs
diffusion --> NSSM
TIS --> NSSM
CT --> NSSM
")
```

::: {.callout-note collapse="true"}
## Mermaid code

```{r}
#| echo: true
#| eval: false
DiagrammeR::mermaid("
graph LR

TS[time<br />series]
ARIMA[autoregressive<br />models]
TIS[time<br />invariant<br />systems]
CT[control<br />theory]
NSSM[neural<br />state space<br />models]

TS --> ARIMA

ARIMA --> diffusion
ARIMA --> LLMs

diffusion --> SDEs
diffusion --> NSSM
TIS --> NSSM
CT --> NSSM
")
```
:::
